name: Bootcamp137 - Backend deployment on Azure
run-name: Backend deployment update triggered by ${{ github.actor }}.
on:
  push:
    branches:
      - deployment
    paths:
      - "backend/**"
      - ".github/workflows/backend-deployment.yml"

permissions:
  id-token: write
  contents: write

jobs:
  backend-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          [
            api-gateway,
            file-service,
            notification-service,
            service-registry,
            user-service,
          ]
    defaults:
      run:
        working-directory: backend/${{ matrix.directory }}
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: deployment

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Fetch secrets from Azure Keyvault
        uses: zemoso-int/get-keyvault-secrets@master
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          keyvault: bootcamp-137
          secrets: |
            REGISTRY_LOGIN_SERVER=registry-login-server
            REGISTRY_USERNAME=registry-username
            REGISTRY_PASSWORD=registry-password

      - name: "Docker Login"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build the backend image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY_LOGIN_SERVER }}/bootcamp137-backend-${{ matrix.directory }}:${{ github.sha }}
          context: backend/${{ matrix.directory }}

  backend-update-manifest:
    runs-on: ubuntu-latest
    needs: backend-build-push
    defaults:
      run:
        working-directory: kubernetes-manifests/deployments/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: deployment

      - name: Fetch secrets from Azure Keyvault
        uses: zemoso-int/get-keyvault-secrets@master
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          keyvault: bootcamp-137
          secrets: |
            REGISTRY_LOGIN_SERVER=registry-login-server

      - name: Update image tag
        run: |
          sed -i 's|image: .*|image: ${{ env.REGISTRY_LOGIN_SERVER }}/bootcamp137-backend-api-gateway:${{ github.sha }}|' api-gateway-deployment.yml
          sed -i 's|image: .*|image: ${{ env.REGISTRY_LOGIN_SERVER }}/bootcamp137-backend-file-service:${{ github.sha }}|' file-service-deployment.yml
          sed -i 's|image: .*|image: ${{ env.REGISTRY_LOGIN_SERVER }}/bootcamp137-backend-notification-service:${{ github.sha }}|' notification-service-deployment.yml
          sed -i 's|image: .*|image: ${{ env.REGISTRY_LOGIN_SERVER }}/bootcamp137-backend-service-registry:${{ github.sha }}|' service-registry-deployment.yml
          sed -i 's|image: .*|image: ${{ env.REGISTRY_LOGIN_SERVER }}/bootcamp137-backend-user-service:${{ github.sha }}|' user-service-deployment.yml

      - name: Get the Commit author email
        run: |
          git fetch origin ${GITHUB_REF:11}
          EMAIL=$(git log -1 --pretty=format:'%ae' HEAD)

      - name: Commit the changes
        run: |
          set -x
          cd ${{github.workspace}}
          git config --local user.email "$EMAIL"
          git config --local user.name ${{ github.actor }}
          git pull origin deployment
          git commit -am "Update image tag to ${{ github.sha }}"
          git push -u origin deployment
