name: SonarCloud Notification Backend
on:
  push:
    branches:
      - main # change it to your main branch.
    paths:
      - "backend/**" # give the backend folder name.
      - ".github/workflows/notificationBuild.yml" # Replace it correctly with the path to your file name.
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notification: # Change the job name to a backend microservice name.
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Give the value at most 8 mins.
    defaults:
      run:
        working-directory: ./backend/notification-service # Change the working-directory to your microservice folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis.

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.NOTIFICATIONSERVICE_TOKEN }} # Change the token name accordingly.
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectName=BC137-notification-service -Dsonar.projectKey=zemoso-int_bc137-notification-service
