name: BOOTCAMP126- BACKEND deployment 
run-name: BACKEND deployment update triggered by ${{ github.actor }}.
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'
 
jobs:
  servicesChanged:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend

    outputs:
      changed-services: ${{ steps.set-output.outputs.changed-services }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Determine changed services
        id: set-output
        run: | 
          changed_services=()
          services=("api-gateway" "candidate" "service-registry")  
          backend_workflow_changed=false
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              path=$(echo "$file" | cut -d'/' -f3)
              if [[ "backend.yaml" == $path ]]; then
                  changed_services=("${services[@]}")
                  backend_workflow_changed=true
                  break
              fi
          done

          if [[ $backend_workflow_changed == false ]]; then
              for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                  path=$(echo "$file" | cut -d'/' -f2)
                  already_exists=false
                  for changed in "${changed_services[@]}"; do
                      if [[ $changed == $path ]]; then
                          already_exists=true
                          break
                      fi
                  done
                  if [[ $already_exists == false ]]; then
                      for service in "${services[@]}"; do
                          if [[ $service == $path ]]; then
                              changed_services+=("$path")
                              break
                          fi
                      done  
                  fi
              done
          fi

          json_array="[\"${changed_services[0]}\""
          for i in "${changed_services[@]:1}"; do
              json_array+=",\"$i\""
          done
          json_array+="]"

          echo "::set-output name=changed-services::$json_array"
          echo "Changed services normal: ${changed_services[*]}"

        
  deploy:
    runs-on: ubuntu-latest
    needs: servicesChanged
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        service: ${{fromJson(needs.servicesChanged.outputs.changed-services)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '17'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ secrets.GHCR_USERNAME }}
         password: ${{ secrets.GHCR_PAT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: adding eks-cluster
        env: 
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
        run: |
            aws eks --region $aws_region update-kubeconfig --name $cluster_name
      - name: Run Strategy
        run: |
          cd ${{matrix.service}}
          mvn clean package -Dmaven.test.skip=true
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-backend-${{matrix.service}}:v${{ github.run_number }} .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-backend-${{matrix.service}}:v${{ github.run_number }} ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-backend-${{matrix.service}}:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-backend-${{matrix.service}}:v${{ github.run_number }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-backend-${{matrix.service}}:latest
          kubectl set image deployment/${{ matrix.service }}-deployment ${{ matrix.service }}-container=ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-backend-${{matrix.service}}:v${{ github.run_number }}