name: BOOTCAMP126 - Frontend deployment 
run-name: Frontend deployment update triggered by ${{ github.actor }}.
on:
  push:
    branches:
      - "deployment"
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
        run:
          working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps

      - name: Retrieve the env vars
        run: echo "${{ secrets.FE_ENV }}" > .env

      - name: Build application
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ secrets.GHCR_USERNAME }}
         password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-frontend:v${{ github.run_number }}
            ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-frontend:latest
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: adding eks-cluster and deployment
        env: 
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          IMAGE: ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp126-frontend:v${{ github.run_number }}
        run: |
          aws eks --region $aws_region update-kubeconfig --name $cluster_name
          kubectl set image deployment/frontend-deployment frontend-container=$IMAGE