name: BOOTCAMP126- Mockserver deployment
run-name: Mockserver deployment update triggered by ${{ github.actor }}.
on:
  push:
    branches:
      - "deployment"
    paths:
      - 'frontend/src/data/db.json'
      - '.github/workflows/mockserver.yaml'

jobs:
  build:    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ secrets.GHCR_USERNAME}}
         password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/src/data
          push: true
          tags: | 
            ghcr.io/${{ secrets.GHCR_USERNAME}}/bootcamp126-mockserver:v${{ github.run_number }}
            ghcr.io/${{ secrets.GHCR_USERNAME}}/bootcamp126-mockserver:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: adding eks-cluster
        env: 
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          IMAGE: ghcr.io/${{ secrets.GHCR_USERNAME}}/bootcamp126-mockserver:v${{ github.run_number }}
        run: |
            aws eks --region $aws_region update-kubeconfig --name $cluster_name
            kubectl set image deployment/mockserver-deployment mockserver-container=$IMAGE
            

    

      