apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: bootcamp137
spec:
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce