apiVersion: v1
kind: Service
metadata:
  name: be-service-registry-service
  labels:
    type: service-registry-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 8761
      port: 8761
  selector:
    type: service-registry-pod
