apiVersion: v1
kind: Service
metadata: 
  name: mockserver-service
  labels:
    type: mockserver
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    type: mockserver