apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-file-service-deployment
  labels:
    type: file-service-deployment
spec:
  template:
    metadata:
      name: be-file-service-pod
      labels:
        type: file-service-pod
    spec:
      containers:
        - name: be-file-service-container
          image: znlzcracrtestipd.azurecr.io/bootcamp137-backend-file-service:a055db8150588e80c11d8f27a3383905a174423e
          imagePullPolicy: Always
          resources: {}
          envFrom:
            - secretRef:
                name: database-credentials
            - secretRef:
                name: es-credentials
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: https://bc137-be.dev-apps.io/eureka/

            - name: eureka.instance.hostname
              value: be-file-service-service

            - name: SERVER_PORT_FILE_SERVICE
              value: "9002"
          ports:
            - containerPort: 9002

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: application
                    operator: In
                    values:
                      - bootcamp137

      tolerations:
        - key: "bootcamp"
          operator: "Equal"
          value: "137"
          effect: "NoExecute"

  replicas: 1
  selector:
    matchLabels:
      type: file-service-pod
