apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-service-registry-deployment
  labels:
    type: service-registry-deployment
spec:
  template:
    metadata:
      name: be-service-registry-pod
      labels:
        type: service-registry-pod
    spec:
      containers:
        - name: be-service-registry-container
          image: znlzcracrtestipd.azurecr.io/bootcamp137-backend-service-registry:a055db8150588e80c11d8f27a3383905a174423e
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_PORT
              value: "8761"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: application
                    operator: In
                    values:
                      - bootcamp137

      tolerations:
        - key: "bootcamp"
          operator: "Equal"
          value: "137"
          effect: "NoExecute"

  replicas: 1
  selector:
    matchLabels:
      type: service-registry-pod
