{{- range .Values.deployments}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .deployment_name}}
spec:
  replicas: {{ .replicaCount}}
  selector:
    matchLabels:
      app: {{ .label_name}}
  template:
    metadata:
      labels:
        app: {{ .label_name}}
    spec:
      containers:
      - name: {{ .container_name }}
        image: {{ .image.repository }}
        {{- if .envFrom}}
        envFrom:
          - secretRef:
              name: {{ .envFrom }}
        {{- end }}
        {{- if .env }}
        env: 
        {{- toYaml .env | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .port }}

        {{- if .volumeMounts }}
        volumeMounts:
        {{- toYaml .volumeMounts | nindent 10 }}
        {{- end }}
      imagePullSecrets:
        - name: {{ .imagePullSecrets}}

      {{- if .volumes }}
      volumes:
      {{- toYaml .volumes | nindent 8 }}
      {{- end }}

---
  {{- end }}
